version: "3"

volumes:
    logs:
        driver: local

services:
    composer:
        restart: "no"
        image: composer/composer:php7
        command: install
        working_dir: /var/www
        volumes:
          - ./app:/var/www

    slim:
        image: php:7.1.2-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 8081:8080
        volumes:
            - ./app:/var/www
            - logs:/var/www/logs
        depends_on:
          - composer

