version: "3"

services:
  app:
      build:
        context: .
        dockerfile: php-fpm/Dockerfile
      container_name: app
      working_dir: /var/www
      environment:
          docker: "true"
      ports:
        - "9000:9000"

  app-webserver:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: app-webserver
    ports:
      - 8081:8080
    links:
      - app

